import { useContext, useEffect } from "react";
import { LoadingAllPage } from "../../components/atoms/Loading";
import { AuthContext } from "../../components/contexts/AuthContext";
import { Coupon } from "../../components/organisms/Coupon";

export const metadata = {
  title: "Technology",
  description: "Generated by create next app",
};
const CouponPage = () => {
  const { load, setLoad } = useContext(AuthContext);
  useEffect(() => {
    setLoad(true);
  }, []);
  return (
    <>
      <LoadingAllPage isOpen={load} setIsOpen={setLoad} />
      <Coupon />
    </>
  );
};
export default CouponPage;
