import { ListProductTop } from "../components/organisms/ProductTop";
import { HaderSection } from "../components/organisms/HaderSection";
import { ListProductHome } from "../components/organisms/ListProduct";
import { ListCategoryBottom } from "../components/molecules/ListCategoryBottom";
import { LoadingAllPage } from "../components/atoms/Loading";
import { useContext } from "react";
import { AuthContext } from "../components/contexts/AuthContext";

export const metadata = {
  title: "Technology",
  description: "Generated by create next app",
};
const Home = () => {
  const { load, setLoad } = useContext(AuthContext);
  return (
    <>
      <LoadingAllPage isOpen={load} setIsOpen={setLoad} />
      <HaderSection />
      <div className="container mx-auto">
        <ListProductTop />
        <ListProductHome />
      </div>

      <ListCategoryBottom />
    </>
  );
};
export default Home;
